# Generated by Django 5.1.4 on 2024-12-13 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_area_alter_usuario_apellidos_alter_usuario_nombres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('tecnico', 'Técnico'), ('administrador', 'Administrador'), ('usuario', 'Usuario')], max_length=20),
        ),
    ]
