# Generated by Django 5.1.4 on 2025-01-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_clasificacion_alter_area_options_alter_rol_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$lD7UnlaY5h3DnAucruo1Zo$xL/aUGWCDpVEJCkwArp1qVQhwRRkcCwDWkBk89/1Bds=', max_length=128),
        ),
    ]
