# Generated by Django 5.1.4 on 2025-01-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$Bryg3J0jsk0y5XRRAq3tEc$jc1BOhZbJzUqcItLpWuSkN66kDB2GDF3N6g2Cr8A1fM=', max_length=128),
        ),
    ]
