# Generated by Django 5.1.4 on 2025-01-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$Z5vjoSnN8edrH9tTlyixv4$CYpUcMGLjSl9QHJEOOaigE2lAwulQLnHTOX48i4FEIY=', max_length=128),
        ),
    ]
