# Generated by Django 5.1.4 on 2025-01-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$NFRBh6WmbXv5Msod3ndUgm$xkO+vmDq/XMFcZViMTeB92JXs6UqnmHbs/5XNaenYbM=', max_length=128),
        ),
    ]
