# Generated by Django 5.1.4 on 2024-12-13 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('area', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('en_espera', 'En espera'), ('solucionada', 'Solucionada'), ('pendiente', 'Pendiente'), ('en_proceso', 'En proceso')], max_length=20)),
                ('tecnico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tecnico_tasks', to='usuarios.usuario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
    ]
