# Generated by Django 5.1.4 on 2024-12-13 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='asunto',
            new_name='incidencia',
        ),
    ]
