# Generated by Django 5.1.4 on 2024-12-13 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_asunto_task_incidencia'),
        ('usuarios', '0003_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.area'),
        ),
    ]
