# Generated by Django 5.1.4 on 2025-01-09 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_prioridad_alter_task_status_task_prioridad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Finalizada', 'Finalizada'), ('pendiente', 'Pendiente'), ('en_proceso', 'En proceso')], max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.estado'),
        ),
    ]
