# Generated by Django 5.1.4 on 2025-01-15 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_clasificacion_alter_prioridad_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prioridad',
            options={'verbose_name_plural': 'Prioridades'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name_plural': 'Tasks'},
        ),
        migrations.RenameField(
            model_name='clasificacion',
            old_name='clasificacion',
            new_name='nombre_clasificacion',
        ),
        migrations.CreateModel(
            name='NumeroBien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numeros_bien', to='tasks.clasificacion')),
            ],
            options={
                'verbose_name_plural': 'Números de Bienes',
            },
        ),
    ]
