# Generated by Django 5.1.4 on 2025-01-15 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_prioridad_options_alter_task_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='clasificacion',
        ),
        migrations.DeleteModel(
            name='NumeroBien',
        ),
    ]
