# Generated by Django 5.1.4 on 2025-01-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_task_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
