# Generated by Django 5.1.4 on 2025-01-15 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0010_remove_task_clasificacion_delete_numerobien'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Equipos',
            },
        ),
        migrations.CreateModel(
            name='NumeroBien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numeros_bien_inventario', to='tasks.clasificacion')),
            ],
            options={
                'verbose_name_plural': 'Números de Bienes',
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('usuario_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('numero_bien', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipo', to='inventario.numerobien')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='inventario.tipoequipo')),
            ],
            options={
                'verbose_name_plural': 'Equipos',
            },
        ),
    ]
